language: python
python:
  - "3.6"
addons:
  postgresql: "9.4"
install: pip install -r requirements.txt
services: postgresql
before_script:
  - psql -c 'create database dogear_test;' -U postgres
  - psql -c 'create database dogear;' -U postgres
  - make upgrade
script: make test
