"""empty message

Revision ID: 327ccd04c68
Revises: 48ebc8d3a0e
Create Date: 2018-07-26 21:14:55.192376

"""

# revision identifiers, used by Alembic.
revision = '327ccd04c68'
down_revision = 'e9aaa4088c'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('groups',
                    sa.Column('uuid', sa.VARCHAR(), autoincrement=False, nullable=False),
                    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
                    sa.Column('id', sa.INTEGER(), nullable=False),
                    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
                    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
                    sa.PrimaryKeyConstraint('id', name='groups_pkey')
                    )
    ### end Alembic commands ###


def downgrade():
    op.drop_table("groups")
    ### commands auto generated by Alembic - please adjust! ###

    ### end Alembic commands ###
