"""empty message

Revision ID: 4c087f9202a
Revises: 4dced2405f8
Create Date: 2018-08-02 07:30:03.072213

"""

# revision identifiers, used by Alembic.
from sqlalchemy import Integer

revision = '4c087f9202a'
down_revision = '4dced2405f8'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('user_ids', postgresql.ARRAY(Integer), nullable=True, default=[]))
    op.alter_column('groups', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_foreign_key(None, 'groups', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'news', 'users', ['user_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'news', type_='foreignkey')
    op.drop_constraint(None, 'groups', type_='foreignkey')
    op.alter_column('groups', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('groups', 'user_ids')
    ### end Alembic commands ###
