"""empty message

Revision ID: 4d923db91b4
Revises: 40aa1a9694cf
Create Date: 2018-07-24 09:39:26.627240

"""

# revision identifiers, used by Alembic.
revision = '4d923db91b4'
down_revision = '327ccd04c68'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('news',
    sa.Column('uuid', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('picture_url', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint( 'id')
    )



def downgrade():

    op.drop_table('news')
    ### end Alembic commands ###
