"""empty message

Revision ID: 4d923db91b4
Revises: 40aa1a9694cf
Create Date: 2018-07-24 09:39:26.627240

"""

# revision identifiers, used by Alembic.
import sqlalchemy_utils

revision = '4d923db91b4'
down_revision = ''

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    op.create_table('users',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('uuid', sa.String(), nullable=True),
                    sa.Column('username', sa.String(), nullable=True),
                    sa.Column('password', sa.String(), nullable=True),
                    sa.Column('email', sa.String(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('groups',
                    sa.Column('uuid', sa.VARCHAR(), autoincrement=False, nullable=False),
                    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
                    sa.Column('id', sa.INTEGER(), nullable=False),
                    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
                    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
                    sa.PrimaryKeyConstraint('id', name='groups_pkey')
                    )
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('news',
    sa.Column('uuid', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('picture_url', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint( 'id')
    )


    op.create_table('flask_dance_oauth',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('token', sqlalchemy_utils.types.json.JSONType(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )

    op.create_foreign_key(None, 'flask_dance_oauth', 'users', ['user_id'], ['id'], referent_schema='public')
    ### end Alembic commands ###
    op.create_table('feed',
                    sa.Column('uuid', sa.VARCHAR(), autoincrement=False, nullable=False),
                    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
                    sa.Column('id', sa.INTEGER(), nullable=False),
                    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
                    sa.Column('from_user_id', sa.INTEGER(), autoincrement=False, nullable=False),
                    sa.Column('news_id', sa.INTEGER(), autoincrement=False, nullable=False),
                    sa.Column('from_group_id', sa.INTEGER(), autoincrement=False, nullable=False),

                    sa.PrimaryKeyConstraint('id', name='feed_pkey')
                    )



def downgrade():
    op.drop_table('feed')
    op.drop_table('news')
    op.drop_table("groups")
    op.drop_table('flask_dance_oauth')
    op.drop_table('users')
    ### end Alembic commands ###
